export const TRAININGS = [
  // {
  //   id: '1',
  //   title: 'Phronesis training #1 (catch up)',
  //   description: 'Implementation of catch up Phronesis training #1 - Create a test environment',
  //   route: 'training-1',
  // },
  // {
  //   id: '2',
  //   title: 'Phronesis training #2 (catch up)',
  //   description: 'Implementation of catch up Phronesis training #2 - Pay an invoice',
  //   route: 'training-2',
  // },
  // {
  //   id: '11',
  //   title: 'Phronesis training #11 (catch up)',
  //   description: 'Implementation of catch up Phronesis training #11 - Casino deposit page',
  //   route: 'training-11',
  // },
  // {
  //   id: "2-new",
  //   title: 'Phronesis training #2 (new) (catch up)',
  //   description: 'Implementation of Phronesis training #2 - Create invoice retry',
  //   route: 'training-2-new',
  // },
  // {
  //   id: '15',
  //   title: 'Phronesis training #15',
  //   description: 'Implementation of Phronesis training #15 - Casino deposit 3ds',
  //   route: 'training-15',
  // },
  // {
  //   id: '16',
  //   title: 'Phronesis training #16',
  //   description: 'Implementation of Phronesis training #16 - Casino payout form',
  //   route: 'training-16',
  // },
  // {
  //   id: '19',
  //   title: 'Phronesis training #19',
  //   description: 'Implementation of Phronesis training #19 - VIP customers',
  //   route: 'training-19',
  // },
  // {
  //   id: '23',
  //   title: 'Phronesis training #23',
  //   description: 'Implementation of Phronesis training #23 - Integrate Checkout.com gateway',
  //   route: 'training-23',
  // },
  // {
  //   id: '25',
  //   title: 'Phronesis training #25',
  //   description: 'Implementation of Phronesis training #15 - Integrate Checkout.com dispute notifications',
  //   route: 'training-25',
  // },
  // {
  //   id: '31',
  //   title: 'Phronesis training #31',
  //   description: 'Implementation of Phronesis training #31 - Orders Early Access',
  //   route: 'training-31',
  // },
  // {
  //   id: '32',
  //   title: 'Phronesis training #32',
  //   description: 'Implementation of Phronesis training #32 - Support team',
  //   route: 'training-32',
  // },
  // {
  //   id: '33',
  //   title: 'Phronesis training #33',
  //   description: 'Implementation of Phronesis training #33 - Coupons',
  //   route: 'training-33',
  // },
  // {
  //   id: '34',
  //   title: 'Phronesis training #34',
  //   description: 'Implementation of Phronesis training #34 - AML',
  //   route: 'training-34',
  // },
  // {
  //   id: '35',
  //   title: 'Phronesis training #35',
  //   description: 'Implementation of Phronesis training #35 - Shipping rates',
  //   route: 'training-35',
  // },
  // {
  //   id: '36',
  //   title: 'Phronesis training #36',
  //   description: 'Implementation of Phronesis training #36 - Custom domains',
  //   route: 'training-36',
  // },
  // {
  //   id: '37',
  //   title: 'Phronesis training #37',
  //   description: 'Implementation of Phronesis training #37 - Quickbooks integration',
  //   route: 'training-37',
  // },
  {
    id: '47',
    title: 'Phronesis training #47',
    description: 'Implementation of Project 47: Marketing emails',
    route: 'training-47',
  },
  {
    id: '48',
    title: 'Phronesis training #48',
    description: 'Implementation of Project 48: Custom webhooks',
    route: 'training-48',
  },
  {
    id: '49',
    title: 'Phronesis training #49',
    description: 'Implementation of Project 49: Segments',
    route: 'training-49',
  },
  {
    id: '50',
    title: 'Phronesis training #50',
    description: 'Implementation of Project 50: Automated tagging',
    route: 'training-50',
  },
  {
    id: '51',
    title: 'Phronesis training #51',
    description: 'Implementation of Project 51: Value lists',
    route: 'training-51',
  },
  {
    id: '52',
    title: 'Phronesis training #52',
    description: 'Implementation of Project 52: Risk scores',
    route: 'training-52',
  },
  {
    id: '53',
    title: 'Phronesis training #53',
    description: 'Implementation of Project 53: Free trials',
    route: 'training-53',
  },
  {
    id: '54',
    title: 'Phronesis training #54',
    description: 'Implementation of Project 54: Deposits (third time)',
    route: 'training-54',
  },
  {
    id: '55',
    title: 'Phronesis training #55',
    description: 'Implementation of Project 55: Google Sheets (revisited)',
    route: 'training-55',
  },
  {
    id: '56',
    title: 'Phronesis training #56',
    description: 'Implementation of Project 56: Casino Demo Training',
    route: 'training-56',
  },
  {
    id: '57',
    title: 'Phronesis training #57',
    description: 'Implementation of Project 57: Revenue recognition (revisited)',
    route: 'training-57',
  },
  {
    id: '58',
    title: 'Phronesis training #58',
    description: 'Implementation of Project 58: Pricing formulas',
    route: 'training-58',
  },
  {
    id: '59',
    title: 'Phronesis training #59',
    description: 'Implementation of Project 59: Quotes',
    route: 'training-59',
  },
  {
    id: '60',
    title: 'Phronesis training #60',
    description: 'Implementation of Project 60: KYC - Closed eyes detection',
    route: 'training-60',
  },
  {
    id: '61',
    title: 'Phronesis training #61',
    description: 'Implementation of Project 61: KPI Segments',
    route: 'training-61',
  },
  {
    id: '62',
    title: 'Phronesis training #62',
    description: 'Implementation of Project 62: Casino deposit error handling',
    route: 'training-62',
  },
  {
    id: '63',
    title: 'Phronesis training #63',
    description: 'Implementation of Project 63: Allowlists',
    route: 'training-63',
  },
].reverse();
