export const TRAININGS = [
  // {
  //   id: '1',
  //   title: 'Phronesis training #1 (catch up)',
  //   description: 'Implementation of catch up Phronesis training #1 - Create a test environment',
  //   route: 'training-1',
  // },
  // {
  //   id: '2',
  //   title: 'Phronesis training #2 (catch up)',
  //   description: 'Implementation of catch up Phronesis training #2 - Pay an invoice',
  //   route: 'training-2',
  // },
  // {
  //   id: '11',
  //   title: 'Phronesis training #11 (catch up)',
  //   description: 'Implementation of catch up Phronesis training #11 - Casino deposit page',
  //   route: 'training-11',
  // },
  // {
  //   id: "2-new",
  //   title: 'Phronesis training #2 (new) (catch up)',
  //   description: 'Implementation of Phronesis training #2 - Create invoice retry',
  //   route: 'training-2-new',
  // },
  // {
  //   id: '15',
  //   title: 'Phronesis training #15',
  //   description: 'Implementation of Phronesis training #15 - Casino deposit 3ds',
  //   route: 'training-15',
  // },
  // {
  //   id: '16',
  //   title: 'Phronesis training #16',
  //   description: 'Implementation of Phronesis training #16 - Casino payout form',
  //   route: 'training-16',
  // },
  // {
  //   id: '19',
  //   title: 'Phronesis training #19',
  //   description: 'Implementation of Phronesis training #19 - VIP customers',
  //   route: 'training-19',
  // },
  // {
  //   id: '23',
  //   title: 'Phronesis training #23',
  //   description: 'Implementation of Phronesis training #23 - Integrate Checkout.com gateway',
  //   route: 'training-23',
  // },
  // {
  //   id: '25',
  //   title: 'Phronesis training #25',
  //   description: 'Implementation of Phronesis training #15 - Integrate Checkout.com dispute notifications',
  //   route: 'training-25',
  // },
  // {
  //   id: '31',
  //   title: 'Phronesis training #31',
  //   description: 'Implementation of Phronesis training #31 - Orders Early Access',
  //   route: 'training-31',
  // },
  // {
  //   id: '32',
  //   title: 'Phronesis training #32',
  //   description: 'Implementation of Phronesis training #32 - Support team',
  //   route: 'training-32',
  // },
  // {
  //   id: '33',
  //   title: 'Phronesis training #33',
  //   description: 'Implementation of Phronesis training #33 - Coupons',
  //   route: 'training-33',
  // },
  // {
  //   id: '34',
  //   title: 'Phronesis training #34',
  //   description: 'Implementation of Phronesis training #34 - AML',
  //   route: 'training-34',
  // },
  // {
  //   id: '35',
  //   title: 'Phronesis training #35',
  //   description: 'Implementation of Phronesis training #35 - Shipping rates',
  //   route: 'training-35',
  // },
  // {
  //   id: '36',
  //   title: 'Phronesis training #36',
  //   description: 'Implementation of Phronesis training #36 - Custom domains',
  //   route: 'training-36',
  // },
  // {
  //   id: '37',
  //   title: 'Phronesis training #37',
  //   description: 'Implementation of Phronesis training #37 - Quickbooks integration',
  //   route: 'training-37',
  // },
  {
    id: '47',
    title: 'Phronesis training #47',
    description: 'Implementation of Project 47: Marketing emails',
    route: 'training-47',
  },
  {
    id: '48',
    title: 'Phronesis training #48',
    description: 'Implementation of Project 48: Custom webhooks',
    route: 'training-48',
  }
];
