/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageDialog: typeof import('./components/image-dialog.vue')['default']
    PhronesisCard: typeof import('./components/phronesis-card.vue')['default']
    Pill: typeof import('./components/pill.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
