/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/debrief-boilerplate': RouteRecordInfo<'/debrief-boilerplate', '/debrief-boilerplate', Record<never, never>, Record<never, never>>,
    '/training-31/': RouteRecordInfo<'/training-31/', '/training-31', Record<never, never>, Record<never, never>>,
    '/training-31/debrief': RouteRecordInfo<'/training-31/debrief', '/training-31/debrief', Record<never, never>, Record<never, never>>,
    '/training-31/demo': RouteRecordInfo<'/training-31/demo', '/training-31/demo', Record<never, never>, Record<never, never>>,
  }
}
