/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/casino/buy-book/': RouteRecordInfo<'/casino/buy-book/', '/casino/buy-book', Record<never, never>, Record<never, never>>,
    '/casino/deposit/': RouteRecordInfo<'/casino/deposit/', '/casino/deposit', Record<never, never>, Record<never, never>>,
    '/casino/home/': RouteRecordInfo<'/casino/home/', '/casino/home', Record<never, never>, Record<never, never>>,
    '/casino/withdraw/': RouteRecordInfo<'/casino/withdraw/', '/casino/withdraw', Record<never, never>, Record<never, never>>,
    '/training-1/': RouteRecordInfo<'/training-1/', '/training-1', Record<never, never>, Record<never, never>>,
    '/training-11/': RouteRecordInfo<'/training-11/', '/training-11', Record<never, never>, Record<never, never>>,
    '/training-15/': RouteRecordInfo<'/training-15/', '/training-15', Record<never, never>, Record<never, never>>,
    '/training-16/': RouteRecordInfo<'/training-16/', '/training-16', Record<never, never>, Record<never, never>>,
    '/training-19/': RouteRecordInfo<'/training-19/', '/training-19', Record<never, never>, Record<never, never>>,
    '/training-2/': RouteRecordInfo<'/training-2/', '/training-2', Record<never, never>, Record<never, never>>,
    '/training-2-new/': RouteRecordInfo<'/training-2-new/', '/training-2-new', Record<never, never>, Record<never, never>>,
    '/training-31/': RouteRecordInfo<'/training-31/', '/training-31', Record<never, never>, Record<never, never>>,
    '/training-32/': RouteRecordInfo<'/training-32/', '/training-32', Record<never, never>, Record<never, never>>,
    '/training-33/': RouteRecordInfo<'/training-33/', '/training-33', Record<never, never>, Record<never, never>>,
    '/training-34/': RouteRecordInfo<'/training-34/', '/training-34', Record<never, never>, Record<never, never>>,
    '/training-35/': RouteRecordInfo<'/training-35/', '/training-35', Record<never, never>, Record<never, never>>,
  }
}
